apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ol-best-practices
resources:
  - namespace.yaml
  - storage.yaml
  - marquez.yaml
  - registry.yaml
  - rbac.yaml
  - builds.yaml
  - dspa.yaml
  - network-policies.yaml

